#cloud-config
users:
  - name: ${username}
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]    
    ssh_authorized_keys:          
      - ${ssh_public_key}          
package_update: true
package_upgrade: false
packages:
  - vim
write_files:
- path: /var/www/html/index.html
  content: |
    <!DOCTYPE html>  
    <html lang="ru">  
    <head>  
        <meta charset="UTF-8">  
        <meta name="viewport" content="width=device-width, initial-scale=1.0">  
        <title>Привет</title>  
    </head>  
    <body>  
        <h1>Это мой курс Netology!</h1>  
        <p>Это простой пример HTML-документа.</p>  
        <p>Надеюсь, вам понравится картинка из бакета!</p>
        <img src="https://storage.yandexcloud.net/miroshnichenko-15-02/elt.jpg" width="800" height="600">         
    </body>  
    </html>
runcmd:
  - 'export PUBLIC_IPV4=$(curl ifconfig.me)'
  - 'echo     Instance: $(hostname), IP Address: $PUBLIC_IPV4 >>  /var/www/html/index.html'     